### ISSUE TITLE
With JavaScript off, no images are shown.

### ISSUE THREAD

**Issue by brucelawson** [ApoorvSaxena/lozad.js#12]
https://apoorv.pro/lozad.js/demo/

(because no src="" attribute on img elements for fallback. Also, alt attribute is malformed; should be alt="")

**Comment by ApoorvSaxena** [comment]
fixed, thanks for reporting 👍

**Comment by brucelawson** [comment]
Thanks for fixing. I'd wondered about progressively enhancing a conventional img element so &lt;img src="picture.png" alt="" class="lozad">. If no JS, this loads normally, if JS is enabled, lozad can step in and lazy load them. (But that might be wasteful because the browser's pre-renderer might already have fetched the images?)

**Comment by styfle** [comment]
> that might be wasteful because the browser's pre-renderer might already have fetched the images

Yes I believe that would happen.

**Comment by pmourer** [comment]
@ApoorvSaxena can you elaborate on how this was "fixed"? Or point to a PR? Or best practice around this? I am still seeing this issue (which makes sense as the image in question has no `src` attribute). I'm not sure I see a way around this.

**Comment by pmourer** [comment]
Looking at the source for the demo, it looks like the solution employed is the following:
```
<article class="thumb">
  <img class="lozad" data-src="images/thumbs/02.jpg" data-index="2">
  <noscript>
    <img src="images/thumbs/02.jpg" data-index="2">
  </noscript>
  <h2>Image 2</h2>
</article>
```
